// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbFjBjh6GIY4G8nhKCgVXACvJjsfhts5E',
    appId: '1:832519778099:android:0e066621425a05df7d1846',
    messagingSenderId: '832519778099',
    projectId: 'fir-d9456',
    storageBucket: 'fir-d9456.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxAd63W-bYspj2uF5Gbac0N2w5obEgCOk',
    appId: '1:309166316358:ios:82abc9e8a7185af6cb6347',
    messagingSenderId: '309166316358',
    projectId: 'flutter-web-rtc-with-call-kit',
    storageBucket: 'flutter-web-rtc-with-call-kit.firebasestorage.app',
    iosBundleId: 'com.example.flutterWebRtcWithCallKit',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCsBQkZb7QtRc6LBc_s_ecJQufyisa3VaA',
    appId: '1:832519778099:web:04f24c13a217f1697d1846',
    messagingSenderId: '832519778099',
    projectId: 'fir-d9456',
    authDomain: 'fir-d9456.firebaseapp.com',
    storageBucket: 'fir-d9456.firebasestorage.app',
    measurementId: 'G-KSMPPRK8B6',
  );
}
